
external_data_config:
  external_data_csv: data/external/train.csv

raw_data_config: 
  raw_data_csv: data/raw/train.csv
  model_var: ['Temperature','Oxygen','Humidity', 'Prediction']
  train_test_split_ratio: 0.2
  target: Prediction 
  random_state: 111
  new_train_data_csv: data/raw/train_new.csv

processed_data_config:
  train_data_csv: data/processed/forest_fire_train.csv
  test_data_csv:  data/processed/forest_fire_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: random_forest
  registered_model_name: random_forest_model
  remote_server_uri: "http://localhost:1234"
  experiment_ids: "1"
 
random_forest: 
  max_depth: 20
  n_estimators: 30

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
